title: My Media Stack
background: https://images.unsplash.com/photo-1550645612-83f5d594b671?auto=format&fit=crop&w=2560&q=80
cardBlur: sm
theme: dark
color: slate
layout:
  - Media Stack:
      - style: row
        columns: 4
  - System:
      - style: row
        columns: 2
  - AI Services:
      - style: row
        columns: 3
